name       : atkmm
version    : 2.28.0
release    : 11
source     :
    - https://download.gnome.org/sources/atkmm/2.28/atkmm-2.28.0.tar.xz : 4c4cfc917fd42d3879ce997b463428d6982affa0fb660cafcc0bc2d9afcedd3a
license    : LGPL-2.0-or-later
component  : desktop.gtk
summary    : C++ bindings to atk
description: |
    C++ bindings to atk
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(sigc++-2.0)
patterns   :
    - devel :
        - /usr/lib64/atkmm-1.6
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
replaces   :
    - libatkmm
    - devel : libatkmm-devel
    - docs : libatkmm-docs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
