name       : atkmm
version    : 2.28.3
release    : 16
source     :
    - https://download.gnome.org/sources/atkmm/2.28/atkmm-2.28.3.tar.xz : 7c2088b486a909be8da2b18304e56c5f90884d1343c8da7367ea5cd3258b9969
license    : LGPL-2.0-or-later
component  : desktop.gtk
summary    : C++ bindings to atk
description: |
    C++ bindings to atk
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(sigc++-2.0)
patterns   :
    - devel :
        - /usr/lib64/atkmm-1.6
replaces   :
    - libatkmm
    - devel : libatkmm-devel
setup      : |
    %meson_configure -Dbuild-documentation='false'
build      : |
    %ninja_build
install    : |
    %ninja_install
