name       : atkmm
version    : 2.24.2
release    : 10
source     :
    - https://download.gnome.org/sources/atkmm/2.24/atkmm-2.24.2.tar.xz : ff95385759e2af23828d4056356f25376cfabc41e690ac1df055371537e458bd
license    : LGPL-2.0-or-later
component  : desktop.gtk
summary    : C++ bindings to atk
description: |
    C++ bindings to atk
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(sigc++-2.0)
patterns   :
    - devel :
        - /usr/lib64/atkmm-1.6
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
replaces   :
    - libatkmm
    - devel : libatkmm-devel
    - docs : libatkmm-docs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
