name       : atkmm
version    : 2.28.1
release    : 15
source     :
    - https://download.gnome.org/sources/atkmm/2.28/atkmm-2.28.1.tar.xz : 116876604770641a450e39c1f50302884848ce9cc48d43c5dc8e8efc31f31bad
license    : LGPL-2.0-or-later
component  : desktop.gtk
summary    : C++ bindings to atk
description: |
    C++ bindings to atk
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(sigc++-2.0)
patterns   :
    - devel :
        - /usr/lib64/atkmm-1.6
replaces   :
    - libatkmm
    - devel : libatkmm-devel
setup      : |
    %meson_configure -Dbuild-documentation='false'
build      : |
    %ninja_build
install    : |
    %ninja_install
