name        : atkmm
version     : 2.22.7
release     : 3
source      :
    - http://ftp.gnome.org/pub/gnome/sources/atkmm/2.22/atkmm-2.22.7.tar.xz : bfbf846b409b4c5eb3a52fa32a13d86936021969406b3dcafd4dd05abd70f91b
homepage    : http://www.gnome.org
license     :
    - LGPL-2.0
summary     : C++ bindings to atk
builddeps   :
    - pkgconfig(atk)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(glibmm-2.4)
patterns    :
    - devel:
        - /usr/lib64/atkmm-1.6
    - docs:
        - /usr/share/devhelp
        - /usr/share/doc
replaces    :
    - libatkmm
    - devel: libatkmm-devel
    - docs: libatkmm-docs
description : |
    C++ bindings to atk
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
